# Project information
site_url: https://timeseriestographs.com
site_name: tsg2
site_author: Joze Rozanec
site_description: >-
  Package for time series to graph conversion and time series generation from graphs

# Repository
repo_name: jmrozanec/time-series-generator
repo_url: https://github.com/jmrozanec/time-series-generator

# Configuration
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    # Palette toggle for light
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  logo: assets/imgs/logo.png

edit_uri: ""

# Plugins
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          selection:
            filters:
              - "!^_" 
          options:
            show_source: false

# Markdown Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

# Page tree
nav:
  - Home: index.md

  - Documentation:
    - Input/output: documentation/input_output.md
    - Model: documentation/model.md
    - To Time sequence strategy: documentation/strategy_to_time_sequence.md
    - Graph linking strategy: documentation/strategy_linking_graph.md
    - Strategy connecting multiple graphs: documentation/strategy_linking_multi_graphs.md
    - To graph strategy: documentation/strategy_to_graph.md

  - Tutorial: tutorial.ipynb
