[project]
name = "ts2g2"
description = "A package to turn timeseries into graphs and graphs into timeseries"
version = "0.1.0"
authors = [
    { name = "Joze Rozanec", email = "jmrozanec@gmail.com" }
]
dependencies = [
    "networkx==3.2.1"
]

[project.optional-dependencies]
dev = [
    "tox",
    "pre-commit",
    "bump2version"
]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]